"""empty message

Revision ID: f6a44d16f3b7
Revises: 11905fb45633
Create Date: 2019-04-16 17:45:58.502701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a44d16f3b7'
down_revision = '11905fb45633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
